clone:
  git:
    image: plugins/git
    pull: true
    recursive: true

pipeline:

###
# Test PR
###

  test:
    image: rust:1.31-stretch
    environment:
    - RUN_MODE=test
    - DATABASE_HOST=db-postgresql
    - DATABASE_URL=postgresql://transactions:transactions@db-postgresql/transactions
    - RUST_BACKTRACE=1
    - CARGO_HOME=deps
    - PGPASSWORD=a1a1a1a1
    commands:
    - rustup component add rustfmt-preview
    - cargo fmt -- --check
    - apt-get update && apt-get install -y ca-certificates wget gnupg2 clang
    - update-ca-certificates
    - wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | apt-key add -
    - echo "deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
    - apt-get update && apt-get install -y libpq5 postgresql-client-10
    - psql -U postgres -h db-postgresql -c "CREATE ROLE transactions WITH PASSWORD 'transactions' LOGIN REPLICATION" -c "CREATE DATABASE transactions OWNER transactions"
    - psql -U postgres -h db-postgresql -d transactions -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"";
    - mkdir -p /usr/local/cargo/bin || true
    - wget -q https://s3.eu-central-1.amazonaws.com/dumpster.stq/diesel -O /usr/local/cargo/bin/diesel
    - chmod +x /usr/local/cargo/bin/diesel
    - diesel migration run
    - cargo test
    when:
      event: pull_request

###
# Build and deploy to nightly
###

  build:
    image: rust:1.31-stretch
    environment:
    - CARGO_HOME=deps
    commands:
    - apt-get update && apt-get install -y clang
    - cargo build
    - mkdir migrations || true
    when:
      event: push
  build:
    image: rust:1.31-stretch
    environment:
    - CARGO_HOME=deps
    commands:
    - apt-get update && apt-get install -y clang
    - cargo build --release --locked
    - mkdir migrations || true
    when:
      event: tag
  package:
    group: package
    image: plugins/docker
    repo: storiqateam/payments-transactions
    tags:
    - ${DRONE_BRANCH//\//_}
    - ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    secrets:
    - docker_username
    - docker_password
    when:
      event: push
  package:
    image: plugins/docker
    repo: storiqateam/payments-transactions
    build_args:
    - env=release
    tags:
    - '${DRONE_TAG}'
    - latest
    secrets:
    - docker_username
    - docker_password
    when:
      event: tag
  deploy2nightly:
    image: jackthestripper/drone_setimage
    namespace: default
    kind: deployment
    object: payments-transactions
    img_names: storiqateam/payments-transactions
    img_tags: ${DRONE_BRANCH//\//_}${DRONE_BUILD_NUMBER}
    img_cnts: transactions
    secrets:
    - source: k8s_pay_nightly_ca
      target: k8s_ca
    - source: k8s_pay_nightly_user
      target: k8s_user
    - source: k8s_pay_nightly_token
      target: k8s_token
    - source: k8s_pay_nightly_addr
      target: k8s_addr
    when:
      branch: master
      event: push

  deploy2prod:
    image: appleboy/drone-ssh
    host: jumpbox.pay.stq.cloud
    command_timeout: 180
    script: |
      cd ~/payments-infra \
      && git reset --hard \
      && git fetch \
      && git pull origin master \
      && ansible-playbook \
      -i ~/payments-infra/ansible/hosts-production.yml \
      --tags transactions \
      --extra-vars "pay_trx_tag=${DRONE_TAG}" \
      ~/payments-infra/ansible/docker.yml
    secrets:
    - ssh_username
    - ssh_key
    when:
      event: deployment
      environment: production

###
# Notifications and post deploy ops
###


###
# Test services
###

services:
  db-postgresql:
    image: postgres:10-alpine
    environment:
    - POSTGRES_PASSWORD=a1a1a1a1
    when:
      event: pull_request


