version: '3'
services:
  transactions:
    image: transactions
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: transactions
    working_dir: /app
    entrypoint:
      - sh
      - -c
      - sleep 10; diesel migration run; /usr/local/cargo/bin/cargo run server
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://transactions:transactions@transactions-pg/transactions
      - "RUST_LOG=transactions=debug"
    expose:
      - 8000
    ports:
      - 8000:8000
    stdin_open: true
    depends_on:
      - transactions-pg
      - transactions-rabbitmq

  transactions-pg:
    image: postgres:10
    container_name: transactions-pg
    volumes:
      - stq-transactions-postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=transactions
      - POSTGRES_DB=transactions
      - POSTGRES_PASSWORD=transactions
    ports:
      - "5432"

  transactions-rabbitmq:
    image: rabbitmq:3-management
    container_name: transactions-rabbitmq
    volumes:
      - stq-transactions-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672"
      - "15672"

volumes:
  stq-transactions-postgres-data:
  stq-transactions-rabbitmq-data:

networks:
  default:
    external:
      name: payments
