version: '3'
services:
  transactions:
    image: transactions
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: transactions
    working_dir: /app
    entrypoint:
      - sh
      - -c
      - sleep 10; diesel migration run; /usr/local/cargo/bin/cargo run server
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://transactions:transactions@transactions-pg/transactions
      - "RUST_LOG=transactions=debug"
    expose:
      - 8000
    stdin_open: true
    depends_on:
      - transactions-pg

  transactions-pg:
    image: postgres:10
    container_name: transactions-pg
    volumes:
      - stq-transactions-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=transactions
      - POSTGRES_DB=transactions
      - POSTGRES_PASSWORD=transactions
    ports:
      - 5432:5432
  
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_LOGS=debug
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  stq-transactions-postgres-data:

networks:
  default:
    external:
      name: payments
