apiVersion: batch/v1
kind: Job
metadata:
  name: createdb-transactions
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: createdb-transactions
        image: postgres:10-alpine
        command:
        - bash
        - -x
        - -c
        - >
          { PGPASSWORD=transactions psql -U transactions -h postgres -d transactions -ql; }
          || {
          psql -h postgres -d postgres -c "CREATE ROLE transactions WITH PASSWORD 'transactions' LOGIN REPLICATION";
          psql -h postgres -d postgres -c "CREATE DATABASE transactions OWNER transactions";
          psql -h postgres -d transactions -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"' || true; }
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres-password
        - name: PGUSER
          value: postgres

