apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: payments-transactions
  labels:
    stack: payments
    app: transactions
spec:
  selector:
    matchLabels:
      app: transactions
      stack: payments
  replicas: 1
  template:
    metadata:
      name: payments-transactions
      labels:
        app: transactions
        stack: payments
    spec:
      imagePullSecrets:
      - name: stq
      containers:
      - name: transactions
        image: storiqateam/payments-transactions
        ports:
        - containerPort: 8000
        env:
        - name: RUN_MODE
          value: k8s
        - name: RUST_BACKTRACE
          value: "1"
        - name: RUST_LOG
          value: transactions=debug
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_URL
          value: postgresql://transactions:transactions@postgres/transactions
        volumeMounts:
        - name: conf
          mountPath: /app/config/
      volumes:
      - name: conf
        configMap:
          name: transactions
