[server]
host = "0.0.0.0"
port = 8000

[client]
dns_threads = 4
keys_url = "https://keys.stq.cloud"
blockchain_url = "https://blockchain.stq.cloud"

[database]
url = "postgresql://transactions:transactions@transactions-pg/transactions"

[cpu_pool]
size = 1
