[server]
host = "0.0.0.0"
port = 8010

[client]
dns_threads = 4
keys_url = "http://keystore:8000/v1"
blockchain_url = "http://blockchain-gateway:8000/v1"

[database]
url = "postgresql://transactions:transactions@postgres:5432/transactions"

[cpu_pool]
size = 1

[auth]
keys_token = "/bFTJb8nn85j1fIAx+eJYiUUzWFMViN/515Y5cD1afU="
keys_user_id = "72034c43-546c-4b1b-b195-41c8c1ba47f4"

[rabbit]
url = "amqp://guest:guest@localhost:5672//?heartbeat=3&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
restart_subscription_secs = 30

[fee_price]
ethereum = 18000000000
bitcoin = 4
