[server]
host = "0.0.0.0"
port = 8000

[client]
dns_threads = 4
keys_url = "https://keys.stq.cloud"
blockchain_url = "https://blockchain.stq.cloud"

[database]
url = "postgresql://transactions:transactions@localhost:5432/transactions"

[cpu_pool]
size = 1

[rabbit]
url = "amqp://guest:guest@localhost:5672//?heartbeat=15&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
