[server]
host = "0.0.0.0"
port = 8010

[client]
dns_threads = 4
keys_url = "http://localhost:8020/v1"
blockchain_url = "http://localhost:8000/v1"

[database]
url = "postgresql://transactions:transactions@localhost:5432/transactions"

[cpu_pool]
size = 1

[auth]
keys_token = "8lVGyQD6hUIxrg3sOt/UofnDLCa+DGaHmGsuGFapYhk="
keys_user_id = "795a8d5d-1234-431e-bcb5-c467ec6c46ab"

[rabbit]
url = "amqp://guest:guest@localhost:5672//?heartbeat=3&frame_max=131072"
thread_pool_size = 2
connection_timeout_secs = 10
connection_pool_size = 10
restart_subscription_secs = 30

[fee_price]
ethereum = 18000000000
bitcoin = 4
